# Generated by Django 4.2.2 on 2023-07-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_alter_deal_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
