# Generated by Django 4.2.2 on 2023-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_image_products_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_price',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
