# Generated by Django 4.2.2 on 2023-07-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
