# Generated by Django 4.2.2 on 2023-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_products_enteredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='EnteredBy',
            field=models.CharField(max_length=100),
        ),
    ]
