# Generated by Django 4.2.2 on 2023-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctors_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Doctor_Contact_Number',
            field=models.IntegerField(max_length=10),
        ),
    ]
