# Generated by Django 4.2.2 on 2023-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctors_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Doctor_Contact_Number',
            field=models.CharField(max_length=10),
        ),
    ]
