# Generated by Django 4.2.2 on 2023-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctors_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Doctor_Specialisation',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Heart', 'Heart'), ('Pathology', 'Pathology'), ('General', 'General'), ('Family Medicine', 'Family Medicine'), ('Orthopaedic', 'Orthopaedic'), ('Sergery', 'Sergery')], max_length=100),
        ),
    ]
