# Generated by Django 4.2.2 on 2023-07-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_doctors_enteredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='EnteredBy',
            field=models.CharField(max_length=100),
        ),
    ]
